<?php

namespace SV\UserMentionsImprovements\XF\Pub\Controller;

class Account extends XFCP_Account
{
	protected function preferencesSaveProcess(\XF\Entity\User $visitor)
	{
		return parent::preferencesSaveProcess($visitor); // TODO: Change the autogenerated stub
	}
}