<?php

namespace SV\UserMentionsImprovements\XF\Alert;

use XF\Entity\UserAlert;
use XF\Mvc\Entity\Entity;

class Post extends XFCP_Post
{
    public function getTemplateData($action, UserAlert $alert, Entity $content = null)
    {
        return parent::getTemplateData($action, $alert, $content); // TODO: Change the autogenerated stub
    }
}
