<?php

namespace SV\UserMentionsImprovements\XF\Repository;

class UserAlert extends XFCP_UserAlert
{
	public function alert(
		\XF\Entity\User $receiver, $senderId, $senderName,
		$contentType, $contentId, $action, array $extra = []
	)
	{
		if ($this->app()
				->offsetExists('sv_userGroupMentionedIds') && $action == 'mention' && array_key_exists($receiver->user_id, $this->app()->sv_userGroupMentionedIds)
		)
		{
			$extra['fromUserGroupMention'] = $this->app()->sv_userGroupMentionedIds[$receiver->user_id];
		}

		return parent::alert($receiver, $senderId, $senderName, $contentType, $contentId, $action, $extra); // TODO: Change the autogenerated stub
	}

}